#ifndef PRE_DETECTOR_SIGNAL_CONNECT_TRANSMITTING_RECEIVING_H
#define PRE_DETECTOR_SIGNAL_CONNECT_TRANSMITTING_RECEIVING_H

class ConnectSystems
{
public:
    ConnectSystems();
private:
};

#endif //PRE_DETECTOR_SIGNAL_CONNECT_TRANSMITTING_RECEIVING_H
