#ifndef PRE_DETECTOR_SIGNAL_FREQUENCY_MODULATION_2_H
#define PRE_DETECTOR_SIGNAL_FREQUENCY_MODULATION_2_H

#include <modulation_interface.h>

/**
 * Phase modulation (PM) is a modulation scheme in which the phase of a carrier signal is varied in proportion to the amplitude of a modulating signal. Quadrature phase modulation (QPM), also known as quadrature modulation or QAM (Quadrature Amplitude Modulation), is a specific form of phase modulation that simultaneously modulates the amplitude and phase of a carrier signal using two quadrature signals.

The general formula for quadrature phase modulation can be expressed as follows:

\[s(t) = A_c \cdot \cos(2\pi f_c t + \theta(t))\]

Where:
- \(s(t)\) is the modulated signal.
- \(A_c\) is the carrier signal's amplitude.
- \(f_c\) is the carrier frequency.
- \(\theta(t)\) is the phase modulation signal, which is a function of time.

In quadrature modulation, the phase modulation signal \(\theta(t)\) is typically represented as the sum of two components, one for the in-phase (I) and one for the quadrature (Q) component. These components are typically represented as \(\theta_I(t)\) and \(\theta_Q(t)\), respectively.

So, the specific formula for quadrature phase modulation can be written as:

\[s(t) = A_c \cdot \cos(2\pi f_c t + \theta_I(t)) \cdot \cos(2\pi f_c t + \theta_Q(t))\]

In practical applications, the in-phase and quadrature components are often generated using baseband signals, and the modulated signal is generated by combining these two components, which are phase-shifted by 90 degrees (π/2 radians) with respect to each other.

Quadrature phase modulation is commonly used in digital communication systems, such as QAM (Quadrature Amplitude Modulation), where both amplitude and phase variations are used to represent digital data symbols.*/


/**Спектральная эффективность. При модуляции крайне важно эффективно использовать доступную полосу пропускания.
 * Различные схемы модуляции имеют разную спектральную эффективность.
 * Например, QAM (квадратурная амплитудная модуляция) может передавать несколько битов на символ,
 * тем самым более эффективно используя полосу пропускания по сравнению с более простыми схемами,
 * такими как амплитудная модуляция (AM).*/

//! написал хуетень!

class FrequencyModulation final : public IModulation
{
public:
    explicit FrequencyModulation(double amplitude,
                                 double freq,
                                 double central_frequency = 433 * 10e6,
                                 double modulation_rate = 4096);

    std::vector<double> modulate(const std::vector<double>& initial_signal) final;
private:
    [[nodiscard]] std::vector<double> integrate(const std::vector<double>& signal) const;

private:
    double _amplitude;
    double _sample_freq;
    double _central_frequency;
    double _modulation_rate;
};

#endif //PRE_DETECTOR_SIGNAL_FREQUENCY_MODULATION_2_H
